apiVersion: v1
kind: Service
metadata:
  name: node-app-service
spec:
  # CRITICAL: This selector must match the Pod label (app: node-app)
  selector:
    app: node-app
  
  # NodePort allows external access via a host IP and a high port (e.g., 3xxxx)
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000      # The port the Service listens on
      # CRITICAL: targetPort must match the containerPort (80)
      targetPort: 3000