apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: node-app-rollout # Change name from deploy to rollout
spec:
  replicas: 10
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app-container
        # Stable version image
        image: docker.io/yvmr/nap1:latest 
        ports:
        - containerPort: 3000
  # --- Add the Canary Strategy ---
  strategy:
    canary:
      # Define the steps for the rollout
      steps:
      - setWeight: 20 # Route 20% of traffic to the new version
      - pause: {}     # Wait indefinitely for manual approval (or use duration: 60s)
      - setWeight: 50 # Route 50% of traffic to the new version
      - pause: {duration: 60s} # Wait 60 seconds
      - setWeight: 80 # Route 80% of traffic
      - pause: {}
      - setWeight: 100 # Promote to 100% (the rest of the rollout is automatic)
